name: ${rootProject.name}
main: ${group}
version: ${version}
api-version: 1.16
commands:
  fichatgpt:
    description: cmd
    aliases: [fichat,figpt,ficg]
permissions:
  fichatgpt.use:
    default: true
  fichatgpt.chat:
    default: op
  fichatgpt.command.delete:
    default: op
  fichatgpt.command.remove:
    default: true
  fichatgpt.command.reload:
    default: op